version: "2.0"

services:

  base_api:
    container_name: weather_middleware
    restart: always
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/srv/api
      - ./dockerfiles/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    restart: always
    volumes:
      - ./:/srv/api